version: '2'

services:
    nginx:
        build:
            context: ./
            dockerfile: Dockerfile
        domainname: lib-use.dev
        volumes:
            - .:/var/dev
#        links:
#            - php
        ports:
            - 80:80
        networks:
            - backend

    php:
        image: php:7.4-fpm
        volumes:
            - .:/var/dev
        ports:
            - 9000:9000
        networks:
            - backend

networks:
    backend:
        driver: bridge
